[project]
name = "hcr-stich"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dask>=2025.2.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
